<a href="https://colab.research.google.com/gist/priyanshu-b20/90008749e287785025276fc93612e476/xor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

In [0]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [0]:
def sigmoid_p(x):
    return (x)*(1-(x))

In [0]:
w1 = np.random.randn(2, 2)
b1 = np.random.randn(1, 2)
w2 = np.random.randn(2, 1)
b2 = np.random.randn(1, 1)

In [162]:
w1,b1,w2,b2

(array([[-0.38508228, -0.676922  ],
        [ 0.61167629,  1.03099952]]),
 array([[ 0.93128012, -0.83921752]]),
 array([[-0.30921238],
        [ 0.33126343]]),
 array([[0.97554513]]))

In [0]:
for r in range(10000):
     layer1 = sigmoid(X @ w1 + b1)
     ans = sigmoid(layer1 @ w2 + b2)
     err = y - ans
     
     dans = err * sigmoid_p(ans)
     errlayere1 = dans @ w2.T
     dlayer1 = errlayere1 * sigmoid_p(layer1)
     
     w2 += layer1.T @ dans * 0.1
     b2 += sum(dans) * 0.1
     w1 += x.T @ dlayer1 * 0.1
     b1 += sum(dlayer1) * 0.1

In [177]:
ans

array([[0.01944075],
       [0.97879575],
       [0.97879518],
       [0.02781577]])

In [178]:
err

array([[-0.01944075],
       [ 0.02120425],
       [ 0.02120482],
       [-0.02781577]])